jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
language: ruby
rvm: 2.7
cache:
  bundler: true
before_script: bundle exec rake vendor:linux
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
