dist: bionic
language: ruby
rvm: 2.7
cache:
  bundler: true
before_script: bundle exec rake vendor:linux
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
